_target_: watchmal.model.grant_gnn.ResGateConv_v2
<<<<<<< Updated upstream
in_channels: 2
=======
in_channels: 4
>>>>>>> Stashed changes
conv_in_channels: [64, 128, 256]
linear_out_features: [128, 64, 32, 2]
dropout: 0.15