

entity: erwanlbv
project: WatChMaL
name:  untrained e- energie 200k

tags: 
  - e
  - 200k
  - regression
  - energy
  - 40k params
  - untrained

job_type: untrained test
notes:  "Test d'une small_resgated sur la bdd test de e-."