

entity: erwanlbv
project: WatChMaL
name:  train e- energie 200k

tags: 
  - e
  - 200k
  - regression
  - energy
  - 40k params

job_type: train / val
notes:  "Régression pour l'énergie de small_resgated sur la bdd 1_20 e-.  "