

entity: erwanlbv
project: WatChMaL
name: untrained e | mu

tags: 
  - e
  - mu
  - 400k
  - classification
  - small resgated
  - untrained

job_type: untrained test
notes:  "Test d'un small resgated sur la bdd de test e | mu"
