

entity: erwanlbv
project: WatChMaL
name: train e | mu 

tags: 
  - e
  - mu
  - 400k
  - classification
  - small resgated

job_type: train / val
notes:  "Classification sur 400k e mu pour la bdd 1_20"
