

entity: erwanlbv
project: WatChMaL
name: untrained mu- energie 

tags: 
  - mu
  - regression
  - energy
  - 200k
  - 40k params
  - untrained

job_type: untrained test
notes:  "Test regression de l'énergie sur 200k mu (100-1kMeV énergie cinétique)"