

entity: erwanlbv
project: WatChMaL
name: mu- energie 1 - 20

tags: 
  - mu
  - regression
  - energy
  - 40k model params

job_type: train / val
notes:  "Regression de l'énergie sur 200k mu (100-1kMeV)"