

entity: erwanlbv
project: WatChMaL

tags: 
  - e/mu 200k
  - classification
  - small resgated
  - 'features: t_c'
  - 'edges: hits'
  - with thresholds

job_type: train / val
notes:  "Impact de la transformation threshold sur charge de 0.15 à 1000"

#"Run to observe node features (time + hits) against (time + charge)"
#tags: 
  # - "t_hits vs t_c"
  # - "features: t_c"  
  # - "edges: hits"
