report_interval: 1

data_loaders:
  test:
    split_key: test_idxs
    is_graph: True
    drop_last: True 

    pin_memory: False
    seed: null
    num_workers: 0
<<<<<<< Updated upstream
    batch_size: 1 # if multi-gpu it will be 1 for each process
=======
    batch_size: 1
>>>>>>> Stashed changes
    