_target_: watchmal.engine.classification.ClassifierEngine

truth_key: 'target'

flatten_model_output: False
prediction_threshold: 0.5
# Mais tu sers à rien toi ?
# label_set:
#   - 0  # Would be 0 (First label - for a softmax argmax call for ex.)
#   - 1  # Would be 1 (Second label)