epochs: 500

val_interval: 30 # Print status on the gradient descent every val_interval step

checkpointing: False

# the parameters are given to get_data_loader in data_utils.py
data_loaders:

  train:
    split_key: train_idxs 
    is_graph: True
    drop_last: True 

    pin_memory: True
    seed: 5
    num_workers: 2     
    batch_size: 256
    
  validation:
    split_key: val_idxs
    is_graph: True
    drop_last: True 

    pin_memory: True
    #seed: 5
    num_workers: 2     
    batch_size: 256
