epochs: 100

val_interval: 10 # (Validation every batch_size * val_interval events)
num_val_batches: 5

checkpointing: False

# the parameters are given to get_data_loader in data_utils.py
data_loaders:

  train:
    split_key: train_idxs 
    is_graph: True
    drop_last: True 

    pin_memory: True
    seed: 5
    num_workers: 2     
    batch_size: 1024
    
  validation:
    split_key: val_idxs
    is_graph: True
    drop_last: True 

    pin_memory: True
    seed: 5
    num_workers: 2     
    batch_size: 1024
