master_port: 12355
gpu_list: [] 
kind: gnn

launch_wandb: True

defaults:
    - data/dataset: e_train_200k_energy_hk
    - data/transforms: e_200k_energy

    #- tasks/evaluate : pretrain_graph_batch_log_evaluate
    - tasks/train: graph_gpu_train_val

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential    
    #- sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: small_resgated_regression_2in_1out
    - engine: gnn_regresser
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: huber
    
    - wandb: e_200k_energy
    - _self_