master_port: 12355
gpu_list: [] 
kind: gnn

launch_wandb: True

defaults:
    - data/dataset: e_mu_test_400k_hk
    - data/transforms: e_mu_11_13_400k_eventType 

    # Notice no restore_state
    - tasks/evaluate: batch_log_untrained_graph

    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential
    - loss@tasks.evaluate.loss: cross_entropy

    - model: small_resgated_classification_2in_2out
    - engine: gnn_classifier
    
    - wandb: e_mu_untrained_400k
    - _self_