master_port: 12355
gpu_list: [] 
kind: gnn

launch_wandb: True

defaults:
    - data/dataset: e_pi0_train_400k_hk
    - data/transforms: e_pi0_11_111_400k_eventType 

    - tasks/train: graph_gpu_train_val

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential    

    - loss@tasks.train.loss: cross_entropy
    - optimizers@tasks.train.optimizers: adam

    - model: small_resgated_classification_2in_2out
    - engine: gnn_classifier
    
    - wandb: e_pi0_train_400k
    - _self_