gpu_list: [] 
kind: gnn

launch_wandb: True

defaults:
    - data/dataset: test_e_mu_hk_christine_small
    - data/transforms: emu_norm_X_hits_time_Y_none 

    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: graph_test

    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: emu_small_grant_newconfig_4in_2out
    - engine: gnn_classifier
    - loss@tasks.evaluate.loss: cross_entropy
    
    - wandb: test_run
    - _self_