gpu_list: [] 
kind: gnn
master_port: 12355

launch_wandb: True

defaults:
    - data/dataset: emu_hk_christine_small
    - data/transforms: emu_norm_X_time_charge_Y_none 

    - tasks/train: graph_gpu_train_val
    - tasks/restore_best_state: empty_restore_best_state
    #- tasks/evaluate: graph_batch_log_evaluate

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential    
    #- sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: emu_small_grant_newconfig_2in_2out
    - engine: gnn_classifier
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.evaluate.loss: cross_entropy
    
    - wandb: wandb_hk_christine_small
    - _self_