gpu_list: []
seed: null

dump_path: './outputs/'
kind: cnn


defaults:
    - data/h5_dataset: hk_cnn_no_mPMTs # hk for cnn

<<<<<<< Updated upstream
    - tasks/train: cnn_gpu_train_val
=======
    - tasks/train: gpu_cnn_train_val
>>>>>>> Stashed changes
#    - tasks/evaluate: cnn_test

    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    #- sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential

    - tasks/restore_best_state: restore_best_state

    - model: resnet18
    - engine: cnn_classifier
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: cross_entropy

    - _self_
