master_port: 12355
gpu_list: [] 
kind: gnn

launch_wandb: True

defaults:
    - data/dataset: mu_test_200k_energy_hk
    - data/transforms: mu_200k_energy

    # No restore best_state bc untrained
    - tasks/evaluate : batch_log_untrained_graph

    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential
    - loss@tasks.evaluate.loss: huber

    - model: small_resgated_regression_2in_1out
    - engine: gnn_regresser
    
    - wandb: mu_200k_energy_untrained_test
    - _self_