gpu_list: [] 
seed: null

kind: gnn
launch_wandb: True

defaults:
    - data/dataset: hk_emu_christine
    - data/transforms: emu_class_charge_time_norm_transforms # data/transforms is available for graphs only

    - tasks/train: TEST_cpu_graph
    - tasks/evaluate: graph_small_test
    - tasks/restore_best_state: restore_best_state

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: TEST_resgated_2channels
    - engine: gnn_regresser
    - loss@tasks.train.loss: cross_entropy
    - optimizers@tasks.train.optimizers: adam
    - wandb: wandb_config

    
    - _self_