gpu_list: [] 
seed: null

dump_path: ".outputs"
kind: gnn
launch_wandb: True

defaults:
    - data/dataset: from_fully_processed
    - data/transforms: emu_class_hits_time_norm_transforms # data/transforms is available for graphs only

    - tasks/train: graph_gpu_train_val
    #- tasks/evaluate: graph_small_test
    #- tasks/restore_best_state: restore_best_state

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    #- sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: resgnn
    - engine: gnn_classifier
    - loss@tasks.train.loss: cross_entropy
    - optimizers@tasks.train.optimizers: adam

    - _self_