#gpu_list: [0, 1] 
gpu_list: []
seed: null
dump_path: ./outputs/

defaults:
    - data/dataset: HK_gnn # data/dataset for previous config
    - data/transforms: grant_transforms

    - model: gcn
    - engine: classifier

    - tasks/train: grant_gnn_train
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test

    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: cross_entropy
    
    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_random    
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential
    - _self_