gpu_list: [] 
seed: null

dump_path: /sps/t2k/eleblevec/updated_watchmal/outputs/test
kind: gnn

defaults:
    - data/dataset: betamode_hk_gnn
    - data/transforms: emu_class_hits_time_norm_transforms # data/transforms is available for graphs only

    - tasks/train: graph_small_train_val
    - tasks/evaluate: graph_small_test
    - tasks/restore_best_state: restore_best_state

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: model_for_testing
    - engine: gnn_classifier
    - loss@tasks.train.loss: cross_entropy
    - optimizers@tasks.train.optimizers: adam

    
    - _self_