gpu_list: [] 
seed: null # Deprecated, set the seed in the tasks folder instead

dump_path: ./outputs/
kind: cnn

defaults:
    - data/h5_dataset: hk_small_cnn_no_mPMTs

    - tasks/train: cnn_small_train_val
    - tasks/evaluate: cnn_small_test
    - tasks/restore_best_state: restore_best_state

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_random    
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: resnet18
    - engine: cnn_classifier
    - optimizers@tasks.train.optimizers: adam
    - loss@tasks.train.loss: cross_entropy
    
    - _self_